const SET_LOADING = 0
const FETCH_COMPLETE = 1
const HANDLE_INPUT_CHANGES = 2
const SUBMIT_COMPLETE = 3
const HANDLE_EDIT_BUTTON = 4
const HANDLE_DELETE_BUTTON = 5
const RESET_FORM = 6

export {SET_LOADING, FETCH_COMPLETE, HANDLE_DELETE_BUTTON, HANDLE_EDIT_BUTTON, HANDLE_INPUT_CHANGES, RESET_FORM, SUBMIT_COMPLETE}